name: stacked_sheets

description: "An advanced, overlay-driven bottom sheet stack with fluid 3D parallax scaling and custom gesture dismissals."

version: 0.0.2

repository: "https://github.com/mrityudata/stacked_sheets"
issue_tracker: "https://github.com/mrityudata/stacked_sheets/issues"

topics:
  - ui
  - bottom-sheet
  - animation
  - overlay
  - parallax

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
